; LGPL3+ Copyright 2025 by Sean Conner.
; Tokens for Color BASIC, Extended Color BASIC, Disk Exetended Color BASIC

;********************************************************************
;	Command tokens
;********************************************************************

CB.CMD_min	equ	$80
CB.CMD_FOR	equ	$80
CB.CMD_GO	equ	$81
CB.CMD_REM	equ	$82
CB.CMD_REM_apos	equ	$83
CB.CMD_ELSE	equ	$84
CB.CMD_IF	equ	$85
CB.CMD_DATA	equ	$86
CB.CMD_PRINT	equ	$87
CB.CMD_ON	equ	$88
CB.CMD_INPUT	equ	$89
CB.CMD_END	equ	$8A
CB.CMD_NEXT	equ	$8B
CB.CMD_DIM	equ	$8C
CB.CMD_READ	equ	$8D
CB.CMD_RUN	equ	$8E
CB.CMD_RESTORE	equ	$8F
CB.CMD_RETURN	equ	$90
CB.CMD_STOP	equ	$91
CB.CMD_POKE	equ	$92
CB.CMD_CONT	equ	$93
CB.CMD_LIST	equ	$94
CB.CMD_CLEAR	equ	$95
CB.CMD_NEW	equ	$96
CB.CMD_CLOAD	equ	$97
CB.CMD_CSAVE	equ	$98
CB.CMD_OPEN	equ	$99
CB.CMD_CLOSE	equ	$9A
CB.CMD_LLIST	equ	$9B
CB.CMD_SET	equ	$9C
CB.CMD_RESET	equ	$9D
CB.CMD_CLS	equ	$9E
CB.CMD_MOTOR	equ	$9F
CB.CMD_SOUND	equ	$A0
CB.CMD_AUDIO	equ	$A1
CB.CMD_EXEC	equ	$A2
CB.CMD_SKIPF	equ	$A3
CB.CMD_TAB	equ	$A4
CB.CMD_TO	equ	$A5
CB.CMD_SUB	equ	$A6
CB.CMD_THEN	equ	$A7
CB.CMD_NOT	equ	$A8
CB.CMD_STEP	equ	$A9
CB.CMD_OFF	equ	$AA
CB.CMD_ADD	equ	$AB
CB.CMD_MINUS	equ	$AC
CB.CMD_MUL	equ	$AD
CB.CMD_DIV	equ	$AE
CB.CMD_POWER	equ	$AF
CB.CMD_AND	equ	$B0
CB.CMD_OR	equ	$B1
CB.CMD_GT	equ	$B2
CB.CMD_EQ	equ	$B3
CB.CMD_LT	equ	$B4
CB.CMD_max	equ	$B4

ECB.CMD_min	equ	$B5
ECB.CMD_DEL	equ	$B5
ECB.CMD_EDIT	equ	$B6
ECB.CMD_TRON	equ	$B7
ECB.CMD_TROFF	equ	$B8
ECB.CMD_DEF	equ	$B9
ECB.CMD_LET	equ	$BA
ECB.CMD_LINE	equ	$BB
ECB.CMD_PCLS	equ	$BC
ECB.CMD_PSET	equ	$BD
ECB.CMD_PRESET	equ	$BE
ECB.CMD_SCREEN	equ	$BF
ECB.CMD_PCLEAR	equ	$C0
ECB.CMD_COLOR	equ	$C1
ECB.CMD_CIRCLE	equ	$C2
ECB.CMD_PAINT	equ	$C3
ECB.CMD_GET	equ	$C4
ECB.CMD_PUT	equ	$C5
ECB.CMD_DRAW	equ	$C6
ECB.CMD_PCOPY	equ	$C7
ECB.CMD_PMODE	equ	$C8
ECB.CMD_PLAY	equ	$C9
ECB.CMD_DLOAD	equ	$CA
ECB.CMD_RENUM	equ	$CB
ECB.CMD_FN	equ	$CC
ECB.CMD_USING	equ	$CD
ECB.CMD_max	equ	$CD

DECB.CMD_min	equ	$CE
DECB.CMD_DIR	equ	$CE
DECB.CMD_DRIVE	equ	$CF
DECB.CMD_FIELD	equ	$D0
DECB.CMD_FILES	equ	$D1
DECB.CMD_KILL	equ	$D2
DECB.CMD_LOAD	equ	$D3
DECB.CMD_LSET	equ	$D4
DECB.CMD_MERGE	equ	$D5
DECB.CMD_RENAME	equ	$D6
DECB.CMD_RSET	equ	$D7
DECB.CMD_SAVE	equ	$D8
DECB.CMD_WRITE	equ	$D9
DECB.CMD_VERIFY	equ	$DA
DECB.CMD_UNLOAD	equ	$DB
DECB.CMD_DSKINI	equ	$DC
DECB.CMD_BACKUP	equ	$DD	
DECB.CMD_COPY	equ	$DE
DECB.CMD_DSKI$	equ	$DF
DECB.CMD_DSKO$	equ	$E0
DECB.CMD_DOS	equ	$E1
DECB.CMD_max	equ	$E1

SECB.CMD_min	equ	$E2
SECB.CMD_WIDTH	equ	$E2
SECB.CMD_PALLET	equ	$E3
SECB.CMD_HSCREEN equ	$E4
SECB.CMD_LPOKE	equ	$E5
SECB.CMD_HCLS	equ	$E6
SECB.CMD_HCOLOR	equ	$E7
SECB.CMD_HPAINT	equ	$E8
SECB.CMD_HCIRCLE equ	$E9	
SECB.CMD_HLINE	equ	$EA
SECB.CMD_HGET	equ	$EB
SECB.CMD_HPUT	equ	$EC
SECB.CMD_HBUFF	equ	$ED
SECB.CMD_HPRINT	equ	$EE
SECB.CMD_ERR	equ	$EF
SECB.CMD_BRK	equ	$F0
SECB.CMD_LOCATE	equ	$F1
SECB.CMD_HSTAT	equ	$F2
SECB.CMD_HSET	equ	$F3
SECB.CMD_HRESET	equ	$F4
SECB.CMD_HDRAW	equ	$F5
SECB.CMD_CMP	equ	$F6
SECB.CMD_RGB	equ	$F7
SECB.CMD_ATTR	equ	$F8
SECB.CMD_max	equ	$F8

;********************************************************************
;	Function tokens - all start with $FF
;********************************************************************

CB.FN_min	equ	$80
CB.FN_SGN	equ	$80
CB.FN_INT	equ	$81
CB.FN_ABS	equ	$82
CB.FN_USR	equ	$83
CB.FN_RND	equ	$84
CB.FN_SIN	equ	$85
CB.FN_PEEK	equ	$86
CB.FN_LEN	equ	$87
CB.FN_STR	equ	$88
CB.FN_VAL	equ	$89
CB.FN_ASC	equ	$8A
CB.FN_CHR	equ	$8B
CB.FN_EOF	equ	$8C
CB.FN_JOYSTK	equ	$8D
CB.FN_LEFT	equ	$8E
CB.FN_RIGHT	equ	$8F
CB.FN_MID$	equ	$90
CB.FN_POINT	equ	$91
CB.FN_INKEY	equ	$92
CB.FN_MEM	equ	$93
CB.FN_max	equ	$93

ECB.FM_min	equ	$94
ECB.FN_ATN	equ	$94
ECB.FN_COS	equ	$95
ECB.FN_TAN	equ	$96
ECB.FN_EXP	equ	$97
ECB.FN_FIX	equ	$98
ECB.FN_LOG	equ	$99
ECB.FN_POS	equ	$9A
ECB.FN_SQR	equ	$9B
ECB.FN_HEX$	equ	$9C
ECB.FN_VARPTR	equ	$9D
ECB.FN_INSTR	equ	$9E
ECB.FN_TIMER	equ	$9F
ECB.FN_PPOINT	equ	$A0
ECB.FN_STRING$	equ	$A1
ECB.FN_max	equ	$A1

DECB.FN_min	equ	$A2
DECB.FN_CVN	equ	$A2
DECB.FN_FREE	equ	$A3
DECB.FN_LOC	equ	$A4
DECB.FN_LOF	equ	$A5
DECB.FN_MKN$	equ	$A6
DECB.FN_AS	equ	$A7
DECB.FN_max	equ	$A7

SECB.FM_min	equ	$A8
SECB.FN_LPEEK	equ	$A8
SECB.FN_BUTTON	equ	$A9
SECB.FN_HPOINT	equ	$AA
SECB.FN_ERNO	equ	$AB
SECB.FN_ERLIN	equ	$AC
SECB.FN_max	equ	$AC
