; LGPL3+ Copyright 2025 by Sean Conner.
; Tokens for Color BASIC, Extended Color BASIC, Disk Exetended Color BASIC

;********************************************************************
;	Command tokens
;********************************************************************

CB.TC_min	equ	$80
CB.TC_FOR	equ	$80
CB.TC_GO	equ	$81
CB.TC_REM	equ	$82
CB.TC_REM_apos	equ	$83
CB.TC_ELSE	equ	$84
CB.TC_IF	equ	$85
CB.TC_DATA	equ	$86
CB.TC_PRINT	equ	$87
CB.TC_ON	equ	$88
CB.TC_INPUT	equ	$89
CB.TC_END	equ	$8A
CB.TC_NEXT	equ	$8B
CB.TC_DIM	equ	$8C
CB.TC_READ	equ	$8D
CB.TC_RUN	equ	$8E
CB.TC_RESTORE	equ	$8F
CB.TC_RETURN	equ	$90
CB.TC_STOP	equ	$91
CB.TC_POKE	equ	$92
CB.TC_CONT	equ	$93
CB.TC_LIST	equ	$94
CB.TC_CLEAR	equ	$95
CB.TC_NEW	equ	$96
CB.TC_CLOAD	equ	$97
CB.TC_CSAVE	equ	$98
CB.TC_OPEN	equ	$99
CB.TC_CLOSE	equ	$9A
CB.TC_LLIST	equ	$9B
CB.TC_SET	equ	$9C
CB.TC_RESET	equ	$9D
CB.TC_CLS	equ	$9E
CB.TC_MOTOR	equ	$9F
CB.TC_SOUND	equ	$A0
CB.TC_AUDIO	equ	$A1
CB.TC_EXEC	equ	$A2
CB.TC_SKIPF	equ	$A3
CB.TC_TAB	equ	$A4
CB.TC_TO	equ	$A5
CB.TC_SUB	equ	$A6
CB.TC_THEN	equ	$A7
CB.TC_NOT	equ	$A8
CB.TC_STEP	equ	$A9
CB.TC_OFF	equ	$AA
CB.TC_ADD	equ	$AB
CB.TC_MINUS	equ	$AC
CB.TC_MUL	equ	$AD
CB.TC_DIV	equ	$AE
CB.TC_POWER	equ	$AF
CB.TC_AND	equ	$B0
CB.TC_OR	equ	$B1
CB.TC_GT	equ	$B2
CB.TC_EQ	equ	$B3
CB.TC_LT	equ	$B4
CB.TC_max	equ	$B4

ECB.TC_min	equ	$B5
ECB.TC_DEL	equ	$B5
ECB.TC_EDIT	equ	$B6
ECB.TC_TRON	equ	$B7
ECB.TC_TROFF	equ	$B8
ECB.TC_DEF	equ	$B9
ECB.TC_LET	equ	$BA
ECB.TC_LINE	equ	$BB
ECB.TC_PCLS	equ	$BC
ECB.TC_PSET	equ	$BD
ECB.TC_PRESET	equ	$BE
ECB.TC_SCREEN	equ	$BF
ECB.TC_PCLEAR	equ	$C0
ECB.TC_COLOR	equ	$C1
ECB.TC_CIRCLE	equ	$C2
ECB.TC_PAINT	equ	$C3
ECB.TC_GET	equ	$C4
ECB.TC_PUT	equ	$C5
ECB.TC_DRAW	equ	$C6
ECB.TC_PCOPY	equ	$C7
ECB.TC_PMODE	equ	$C8
ECB.TC_PLAY	equ	$C9
ECB.TC_DLOAD	equ	$CA
ECB.TC_RENUM	equ	$CB
ECB.TC_FN	equ	$CC
ECB.TC_USING	equ	$CD
ECB.TC_max	equ	$CD

DECB.TC_min	equ	$CE
DECB.TC_DIR	equ	$CE
DECB.TC_DRIVE	equ	$CF
DECB.TC_FIELD	equ	$D0
DECB.TC_FILES	equ	$D1
DECB.TC_KILL	equ	$D2
DECB.TC_LOAD	equ	$D3
DECB.TC_LSET	equ	$D4
DECB.TC_MERGE	equ	$D5
DECB.TC_RENAME	equ	$D6
DECB.TC_RSET	equ	$D7
DECB.TC_SAVE	equ	$D8
DECB.TC_WRITE	equ	$D9
DECB.TC_VERIFY	equ	$DA
DECB.TC_UNLOAD	equ	$DB
DECB.TC_DSKINI	equ	$DC
DECB.TC_BACKUP	equ	$DD
DECB.TC_COPY	equ	$DE
DECB.TC_DSKI$	equ	$DF
DECB.TC_DSKO$	equ	$E0
DECB.TC_DOS	equ	$E1
DECB.TC_max	equ	$E1

SECB.TC_min	equ	$E2
SECB.TC_WIDTH	equ	$E2
SECB.TC_PALLET	equ	$E3
SECB.TC_HSCREEN equ	$E4
SECB.TC_LPOKE	equ	$E5
SECB.TC_HCLS	equ	$E6
SECB.TC_HCOLOR	equ	$E7
SECB.TC_HPAINT	equ	$E8
SECB.TC_HCIRCLE equ	$E9
SECB.TC_HLINE	equ	$EA
SECB.TC_HGET	equ	$EB
SECB.TC_HPUT	equ	$EC
SECB.TC_HBUFF	equ	$ED
SECB.TC_HPRINT	equ	$EE
SECB.TC_ERR	equ	$EF
SECB.TC_BRK	equ	$F0
SECB.TC_LOCATE	equ	$F1
SECB.TC_HSTAT	equ	$F2
SECB.TC_HSET	equ	$F3
SECB.TC_HRESET	equ	$F4
SECB.TC_HDRAW	equ	$F5
SECB.TC_CMP	equ	$F6
SECB.TC_RGB	equ	$F7
SECB.TC_ATTR	equ	$F8
SECB.TC_max	equ	$F8

;********************************************************************
;	Function tokens - all start with $FF
;********************************************************************

CB.TF_min	equ	$80
CB.TF_SGN	equ	$80
CB.TF_INT	equ	$81
CB.TF_ABS	equ	$82
CB.TF_USR	equ	$83
CB.TF_RND	equ	$84
CB.TF_SIN	equ	$85
CB.TF_PEEK	equ	$86
CB.TF_LEN	equ	$87
CB.TF_STR	equ	$88
CB.TF_VAL	equ	$89
CB.TF_ASC	equ	$8A
CB.TF_CHR	equ	$8B
CB.TF_EOF	equ	$8C
CB.TF_JOYSTK	equ	$8D
CB.TF_LEFT	equ	$8E
CB.TF_RIGHT	equ	$8F
CB.TF_MID$	equ	$90
CB.TF_POINT	equ	$91
CB.TF_INKEY	equ	$92
CB.TF_MEM	equ	$93
CB.TF_max	equ	$93

ECB.FM_min	equ	$94
ECB.TF_ATN	equ	$94
ECB.TF_COS	equ	$95
ECB.TF_TAN	equ	$96
ECB.TF_EXP	equ	$97
ECB.TF_FIX	equ	$98
ECB.TF_LOG	equ	$99
ECB.TF_POS	equ	$9A
ECB.TF_SQR	equ	$9B
ECB.TF_HEX$	equ	$9C
ECB.TF_VARPTR	equ	$9D
ECB.TF_INSTR	equ	$9E
ECB.TF_TIMER	equ	$9F
ECB.TF_PPOINT	equ	$A0
ECB.TF_STRING$	equ	$A1
ECB.TF_max	equ	$A1

DECB.TF_min	equ	$A2
DECB.TF_CVN	equ	$A2
DECB.TF_FREE	equ	$A3
DECB.TF_LOC	equ	$A4
DECB.TF_LOF	equ	$A5
DECB.TF_MKN$	equ	$A6
DECB.TF_AS	equ	$A7
DECB.TF_max	equ	$A7

	; $A8 not issued---mistake?

SECB.TF_min	equ	$A9
SECB.TF_LPEEK	equ	$AA
SECB.TF_BUTTON	equ	$AB
SECB.TF_HPOINT	equ	$AC
SECB.TF_ERNO	equ	$AD
SECB.TF_ERLIN	equ	$AE
SECB.TF_max	equ	$AE
